-- Paid consultations / service orders.
-- This file adds a separate order flow for YooKassa-paid consultations.

create table if not exists public.service_catalog (
  id bigint generated by default as identity primary key,
  title text not null,
  description text null,
  price_money numeric not null,
  input_schema jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  service_id bigint not null references public.service_catalog(id) on delete restrict,
  status text not null default 'pending_payment',
  auth_provider text not null default 'telegram',
  provider_user_id bigint null,
  username text null,
  input_data jsonb not null default '{}'::jsonb,
  admin_notes text null,
  result_text text null,
  price_money numeric not null,
  pay_method text null,
  payment_id text null,
  paid_at timestamptz null,
  notified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_orders_status_check check (
    status in (
      'pending_payment',
      'new',
      'input_pending',
      'admin_review',
      'in_work',
      'finished',
      'failed',
      'cancelled'
    )
  ),
  constraint service_orders_auth_provider_check check (
    auth_provider in ('telegram', 'vk')
  )
);

create index if not exists service_catalog_active_sort_idx
on public.service_catalog(is_active, sort_order, id);

create index if not exists service_orders_status_created_idx
on public.service_orders(status, created_at);

create index if not exists service_orders_user_created_idx
on public.service_orders(user_id, created_at desc);

create index if not exists service_orders_provider_created_idx
on public.service_orders(auth_provider, created_at desc);

create index if not exists service_orders_payment_id_idx
on public.service_orders(payment_id);

-- Convenience view for admin bots and dashboards.
create or replace view public.service_order_admin_queue as
select
  so.id,
  so.status,
  so.created_at,
  so.updated_at,
  so.notified_at,
  so.auth_provider,
  so.provider_user_id,
  so.username,
  so.input_data,
  so.admin_notes,
  so.result_text,
  sc.title as service_title,
  sc.description as service_description,
  so.price_money,
  so.pay_method,
  so.payment_id
from public.service_orders so
join public.service_catalog sc on sc.id = so.service_id;

-- Compatibility helper for bots that were built around auth_users-like shape.
create or replace view public.auth_users as
select
  u.id,
  case
    when u.vk_real is not null then u.vk_real
    else u.telegram_real
  end as provider_user_id,
  u.username,
  case
    when u.vk_real is not null then 'vk'
    else 'telegram'
  end as auth_provider
from public.users u;

create or replace function public.service_order_set_note_inwork(
  p_order_id bigint,
  p_note text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.service_orders
  set admin_notes = p_note,
      updated_at = now()
  where id = p_order_id
    and status = 'in_work';
end;
$$;

create or replace function public.service_order_complete(
  p_order_id bigint,
  p_result_text text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.service_orders
  set status = 'finished',
      result_text = coalesce(p_result_text, result_text),
      updated_at = now()
  where id = p_order_id
    and status = 'in_work';
end;
$$;

create or replace function public.service_order_fail(
  p_order_id bigint,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.service_orders
  set status = 'failed',
      admin_notes = p_reason,
      updated_at = now()
  where id = p_order_id
    and status = 'in_work';
end;
$$;

-- Example seed. Adjust prices/texts in Supabase before production use.
insert into public.service_catalog (title, description, price_money, sort_order)
select
  'Консультация',
  'Персональная консультация специалиста',
  1000,
  100
where not exists (
  select 1
  from public.service_catalog
  where title = 'Консультация'
);
